apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: dinesykmeldte-lest-topic
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  pool: {{ kafka-pool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 3
    replication: 3
    retentionBytes: -1  # Messages will never be deleted because of disk space
    retentionHours: -1  # Messages will never be timed out
  acl:
    - team: team-esyfo
      application: dinesykmeldte-backend
      access: readwrite
    - team: teamsykmelding
      application: dinesykmeldte-backend
      access: readwrite
