### POST request to isActiveSykmelding

POST http://localhost:8080/api/sykmelding/isActiveSykmelding
Authorization: Bearer {{fakedings_aad_token}}
Content-Type: application/json

{
  "sykmeldtFnr": "{{$pid}}",
  "orgnummer": "{{orgnummer}}"
}
