apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dinesykmeldte-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: dinesykmeldte-backend-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: dinesykmeldte-backend
            envVarPrefix: NAIS_DATABASE
        diskAutoresize: true
        highAvailability: true
        insights:
          enabled: true
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://dinesykmeldte-backend.dev.intern.nav.no"
  webproxy: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: dinesykmeldte
  env:
    - name: ALLOWED_ORIGIN
      value: tjenester-q1.nav.no,www-gcp.dev.nav.no,dinesykmeldte-backend.dev.nav.no
