openapi: 3.0.0
info:
  title: Dinesykmeldte api
  version: 1.0.0
  description: Api for dinesykmeldte
servers:
  - url: 'https://dinesykmeldte-backend.dev.intern.nav.no'
paths:
  /api/minesykmeldte:
    get:
      summary: Getting mine sykmeldte
      operationId: getMineSykmeldte
      responses:
        200:
          $ref: '#/components/responses/MineSykmeldteResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
  /api/sykmelding/{sykmeldingId}/lest:
    parameters:
      - $ref: '#/components/parameters/sykmeldingId'
    put:
      summary: Merk sykmelding som lest
      operationId: updateLestSykmelding
      responses:
        200:
          description: Ok
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
  /api/sykmelding/{sykmeldingId}:
    parameters:
      - $ref: '#/components/parameters/sykmeldingId'
    get:
      summary: Getting sykmelding by sykmeldingId
      operationId: getSykmelding
      responses:
        200:
          $ref: '#/components/responses/SykmeldingResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
  /api/soknad/{soknadId}/lest:
    parameters:
      - $ref: '#/components/parameters/soknadId'
    put:
      summary: Merk søknad som lest
      operationId: updateLestSoknad
      responses:
        200:
          description: Ok
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
  /api/soknad/{soknadId}:
    parameters:
      - $ref: '#/components/parameters/soknadId'
    get:
      summary: Getting søknad by søknadId
      operationId: getSoknad
      responses:
        200:
          $ref: '#/components/responses/SoknadResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
  /api/hendelse/{hendelseId}/lest:
    parameters:
      - $ref: '#/components/parameters/hendelseId'
    put:
      summary: Merk hendelse som lest
      operationId: updateLestHendelse
      responses:
        200:
          description: Ok
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
  /api/virksomheter:
    get:
      summary: Henter virksomheter der innlogget bruker er registrert som leder
      operationId: getVirksomheter
      responses:
        200:
          $ref: '#/components/responses/VirksomheterResponse'
        401:
          description: Unauthorized
        403:
          description: Forbidden

components:
  parameters:
    sykmeldingId:
      in: path
      name: sykmeldingId
      description: SykmeldingId til sykmelding
    soknadId:
      in: path
      name: soknadId
      description: SoknadId til søknad
    hendelseId:
      in: path
      name: hendelseId
      description: HendelseId til hendelse

  responses:
    MineSykmeldteResponse:
      description: List of sykmeldte
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MineSykmeldteList'
    SykmeldingResponse:
      description: Sykmelding
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Sykmelding'
    SoknadResponse:
      description: Søknad
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Soknad'
    VirksomheterResponse:
      description: Virksomheter
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Virksomhet'

  schemas:
    Periode:
      type: object
      required:
        - fom
        - tom
        - type
      properties:
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
        type:
          type: string
          enum:
            - GRADERT
            - AVVENTENDE
            - REISETILSKUDD
            - BEHANDLINGSDAGER
            - AKTIVITET_IKKE_MULIG
    Gradert:
      type: object
      allOf:
        - $ref: '#/components/schemas/Periode'
      properties:
        type:
          type: string
          enum:
            - GRADERT
        grad:
          type: number
          maximum: 100
          minimum: 0
        reisetilskudd:
          type: boolean
    AktivitetIkkeMulig:
      type: object
      allOf:
        - $ref: '#/components/schemas/Periode'
      properties:
        arbeidsrelatertArsak:
          type: object
          properties:
            arsak:
              type: array
              items:
                type: string
                enum:
                  - MANGLENDE_TILRETTELEGGING
                  - ANNET
            beskrivelse:
              type: string
        type:
          type: string
          enum:
            - AKTIVITET_IKKE_MULIG
    Behandlingsdager:
      type: object
      allOf:
        - $ref: '#/components/schemas/Periode'
      properties:
        type:
          type: string
          enum:
            - BEHANDLINGSDAGER
        behandlingsdager:
          type: number
          minimum: 1
          maximum: 1
    Reisetilskudd:
      type: object
      allOf:
        - $ref: '#/components/schemas/Periode'
      properties:
        type:
          type: string
          enum:
            - REISETILSKUDD
    Avventende:
      type: object
      allOf:
        - $ref: '#/components/schemas/Periode'
      properties:
        type:
          type: string
          enum:
            - AVVENTENDE
        tilrettelegging:
          type: string
    MineSykmeldteList:
      type: array
      items:
        $ref: '#/components/schemas/PreviewSykmeldt'
    Sykmelding:
      type: object
      required:
        - id
        - lest
        - startdatoSykefravar
        - navn
        - fnr
        - arbeidsgiver
        - perioder
        - behandler
      properties:
        id:
          type: string
          format: uuid
        startdatoSykefravar:
          type: string
          format: date
        kontaktDato:
          type: string
          format: date
        navn:
          type: string
        fnr:
          $ref: '#/components/schemas/Fnr'
        lest:
          type: boolean
        arbeidsgiver:
          type: object
          required:
            - orgnummer
          properties:
            navn:
              type: string
            orgnummer:
              type: string
            yrke:
              type: string
        perioder:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/Gradert'
              - $ref: '#/components/schemas/AktivitetIkkeMulig'
              - $ref: '#/components/schemas/Behandlingsdager'
              - $ref: '#/components/schemas/Reisetilskudd'
              - $ref: '#/components/schemas/Avventende'
        arbeidsforEtterPeriode:
          type: boolean
        hensynArbeidsplassen:
          type: string
        tiltakArbeidsplassen:
          type: string
        innspillArbeidsplassen:
          type: string
        behandler:
          type: object
          required:
            - navn
          properties:
            navn:
              type: string
            hprNummer:
              type: string
            telefon:
              type: string
    PreviewSykmeldt:
      type: object
      required:
        - narmestelederId
        - orgnummer
        - fnr
        - navn
        - startdatoSykefravar
        - friskmeldt
        - previewSykmeldinger
        - previewSoknader
        - dialogmoter
      properties:
        fnr:
          $ref: '#/components/schemas/Fnr'
        narmestelederId:
          type: string
          format: uuid
        orgnummer:
          type: string
        navn:
          type: string
        startdatoSykefravar:
          type: string
          format: date
        friskmeldt:
          type: boolean
        previewSykmeldinger:
          type: array
          items:
            $ref: '#/components/schemas/PreviewSykmelding'
        previewSoknader:
          type: array
          items:
            $ref: '#/components/schemas/PreviewSoknader'
        dialogmoter:
          type: array
          items:
            $ref: '#/components/schemas/Dialogmote'
    PreviewSykmelding:
      type: object
      required:
        - id
        - fom
        - tom
        - type
        - lest
      properties:
        id:
          type: string
          format: uuid
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
        type:
          type: string
          example: '100%'
        lest:
          type: boolean
    PreviewSoknader:
      required:
        - id
        - status
        - lest
      type: object
      properties:
        id:
          type: string
          format: uuid
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
        lest:
          type: boolean
        sykmeldingId:
          type: string
          format: uuid
        status:
          type: string
        sendtDato:
          type: string
          format: date
        ikkeSendtSoknadVarsel:
          type: boolean
        korrigertBySoknadId:
          type: string
        korrigererSoknadId:
          type: string
    Soknad:
      required:
        - id
        - sykmeldingId
        - fom
        - tom
        - navn
        - fnr
        - lest
        - perioder
        - sporsmal
        - ikkeSendtSoknadVarsel
      type: object
      properties:
        id:
          type: string
          format: uuid
        sykmeldingId:
          type: string
          format: uuid
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
        navn:
          type: string
        fnr:
          $ref: '#/components/schemas/Fnr'
        lest:
          type: boolean
        korrigertBySoknadId:
          type: string
        perioder:
          type: array
          items:
            $ref: '#/components/schemas/Soknadsperiode'
        sporsmal:
          type: array
          items:
            $ref: '#/components/schemas/Sporsmal'
    Soknadsperiode:
      required:
        - fom
        - tom
        - sykmeldingstype
      type: object
      properties:
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
        sykmeldingsgrad:
          type: number
          maximum: 100
          minimum: 0
        sykmeldingstype:
          type: string
          enum:
            - AKTIVITET_IKKE_MULIG
            - AVVENTENDE
            - BEHANDLINGSDAGER
            - GRADERT
            - REISETILSKUDD
    Undersporsmal:
      required:
        - id
        - tag
        - svartype
        - kriterieForVisningAvUndersporsmal
        - svar
      type: object
      properties:
        id:
          type: string
          format: uuid
        tag:
          type: string
        sporsmalstekst:
          type: string
        undertekst:
          type: string
        svartype:
          $ref: '#/components/schemas/SvartypeDTO'
        kriterieForVisningAvUndersporsmal:
          $ref: '#/components/schemas/VisningskriteriumDTO'
        svar:
          type: array
          items:
            $ref: '#/components/schemas/Svar'
        undersporsmal:
          example:
          type: array
          items:
            $ref: '#/components/schemas/Undersporsmal'
    Sporsmal:
      required:
        - id
        - tag
        - sporsmalstekst
        - svartype
        - kriterieForVisningAvUndersporsmal
        - svar
      type: object
      properties:
        id:
          type: string
          format: uuid
        tag:
          type: string
        sporsmalstekst:
          type: string
        undertekst:
          type: string
        svartype:
          $ref: '#/components/schemas/SvartypeDTO'
        kriterieForVisningAvUndersporsmal:
          $ref: '#/components/schemas/VisningskriteriumDTO'
        svar:
          type: array
          items:
            $ref: '#/components/schemas/Svar'
        undersporsmal:
          type: array
          items:
            $ref: '#/components/schemas/Undersporsmal'
    SvartypeDTO:
      type: string
      enum:
        - JA_NEI
        - CHECKBOX
        - CHECKBOX_GRUPPE
        - CHECKBOX_PANEL
        - DATO
        - PERIODE
        - PERIODER
        - TIMER
        - FRITEKST
        - IKKE_RELEVANT
        - PROSENT
        - RADIO_GRUPPE
        - RADIO_GRUPPE_TIMER_PROSENT
        - RADIO
        - TALL
        - RADIO_GRUPPE_UKEKALENDER
        - LAND
        - INFO_BEHANDLINGSDAGER
        - KVITTERING
        - DATOER
        - BELOP
        - KILOMETER
    VisningskriteriumDTO:
      type: string
      enum:
        - JA
        - NEI
        - CHECKED
    Svar:
      required:
        - verdi
      type: object
      properties:
        verdi:
          type: string
    Dialogmote:
      required:
        - id
        - oppgavetype
        - hendelseId
      type: object
      properties:
        id:
          type: string
          format: uuid
        hendelseId:
          type: string
          format: uuid
        oppgavetype:
          type: string
          example: 'DIALOGMOTE_INNKALLING'
        lenke:
          type: string
        tekst:
          type: string
    Fnr:
      type: string
      minLength: 11
      maxLength: 11
      example: '01010112345'
    Virksomhet:
      required:
        - navn
        - orgnummer
      type: object
      properties:
        navn:
          type: string
        orgnummer:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]