apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dinesykmeldte-kafka
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 768Mi
  vault:
    enabled: false
  filesFrom:
    - secret: dinesykmeldte-kafka-user-secret
  kafka:
    pool: nav-dev
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_ENDPOINT_URL
      value: https://flex-syketilfelle.dev.intern.nav.no
    - name: SYKETILLFELLE_SCOPE
      value: api://dev-gcp.flex.flex-syketilfelle/.default