apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dinesykmeldte-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: dinesykmeldte-backend-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: dinesykmeldte-backend
            envVarPrefix: NAIS_DATABASE
        diskAutoresize: true
        highAvailability: true
        insights:
          enabled: true
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://dinesykmeldte-backend.nav.no"
  webproxy: true
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: dinesykmeldte
    outbound:
      external:
        - host: https://pdl-api.prod-fss-pub.nais.io
        - host: https://teamsykmelding-auth-fss-proxy.prod-fss-pub.nais.io
  env:
    - name: ALLOWED_ORIGIN
      value: tjenester.nav.no,www.nav.no
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/pdl-api/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_ENDPOINT_URL
      value: https://teamsykmelding-auth-fss-proxy.prod-fss-pub.nais.io
    - name: SYKETILLFELLE_SCOPE
      value: api://prod-fss.teamsykmelding.teamsykmelding-auth-fss-proxy/.default