apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dinesykmeldte-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: dinesykmeldte-backend-db-instance
        type: POSTGRES_17
        diskSize: 10
        tier: db-custom-2-5120
        databases:
          - name: dinesykmeldte-backend
            envVarPrefix: NAIS_DATABASE
        diskAutoresize: true
        highAvailability: true
        insights:
          enabled: true
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 768Mi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: dinesykmeldte
        - application: oppfolgingsplan
        - application: oppfolgingsplan-frontend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: dialogmote-frontend
          namespace: team-esyfo
          cluster: prod-gcp
    outbound:
      rules:
        - application: flex-syketilfelle
          namespace: flex
          cluster: prod-gcp
      external:
        - host: pdl-api.prod-fss-pub.nais.io
  leaderElection: true
  secureLogs:
    enabled: true
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://prod-gcp.flex.flex-syketilfelle/.default
