name: Build and deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [ checks_requested ]
  workflow_dispatch:

jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/jar-app.yaml@main
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: dinesykmeldte-backend
      java-version: '21'

  deploy-pdl-kafka-alert-dev:
    if: >-
      ${{
        github.actor != 'dependabot[bot]' &&
        (
          github.event_name == 'push' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
        )
      }}
    name: Deploy PDL Kafka alert to dev
    needs: jar-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/pdl-kafka-alert.yaml

  deploy-pdl-kafka-alert-prod:
    if: github.ref_name == 'main'
    name: Deploy PDL Kafka alert to prod
    needs: jar-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/pdl-kafka-alert.yaml
